### ISSUE TITLE
Sometimes progress value is jumped from 0 to 100.

### ISSUE THREAD

**Issue by iraj-wisilica** [tankery/CircularSeekBar#7] opened 2017-09-20 13:35 UTC
The current thumb is at value of 0. When changing the seek bar speedy, the value jumps to 100. I suspect the following code block.

else if (lockAtEnd && lockEnabled) {
mProgress = mMax; // Suspected here.
recalculateAll();
invalidate();
if (mOnCircularSeekBarChangeListener != null) {
mOnCircularSeekBarChangeListener.onProgressChanged(this, mProgress, true);
}
}

**Comment by tankery** [comment] 2017-10-08 11:01
Sorry I can't reproduce this issue.
Maybe because your finger is leave the screen and jump to another side when you move speedy?

If you can reproduce this, can you put more details on your description? Such as the attributes you use, and steps to reproduce this bug, thanks.

**Comment by tankery** [comment] 2018-03-09 08:10
Hi, @iraj-wisilica do you still have trouble on this issue? I'll close this issue in next week if no new feedback comes, since the bug cannot been reproduced.

**Comment by tankery** [comment] 2018-03-22 04:35
Can not reproduce.

**Closed** 2018-03-22 04:34 UTC
Labels: bug
