### ISSUE TITLE
how to make progress color with gradient

### ISSUE THREAD

**Issue by LtotheWT** [tankery/CircularSeekBar#13] opened 2018-07-17 02:53 UTC
i have a drawable with gradient color, but i do not where to implement.
In normal seekbar, the drawable can be set in progressDrawable

**Comment by tankery** [comment] 2018-09-30 11:30
Hi, @LtotheWT 

Unfortunately, this library not support a gradient color yet.

If what you said about "normal seekbar" is [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar) in Android platform, AFAIK, it was implemted by clip the draw to specific progress. But this library use a `Path` to support rounded endpoint, so we can't set a progressDrawable to it.

You can try to set a gradient to `mCircleProgressPaint` to implement the gradient color for now.
And I'll consider this feature request in future version. Thanks.

Duplicate of #4

**Closed** 2018-09-30 11:47 UTC
Labels: enhancement
